#!/bin/bash

# Disha Load Testing - Authenticated Business Endpoints
#
# The two existing scripts (load-test-baseline.sh, load-test-progressive.sh)
# only exercise unauthenticated /health* endpoints, which measure Node's raw
# request-handling ceiling, not real query performance. This script logs in
# for real, pulls real seeded IDs from the running API, and load-tests a mix
# of authenticated read and write business endpoints via a generated wrk Lua
# script — closing the gap flagged in LOAD_TEST_RESULTS.md's "Future Scaling
# Requirements".
#
# Endpoints covered (cycled round-robin per request):
#   GET  /api/v2/students/school/:schoolId
#   GET  /api/v2/assessments/school/:schoolId
#   GET  /api/v2/reports/school/:schoolId/performance
#   POST /api/v2/attendance/bulk (idempotent per student+date — verified
#        against AttendanceService.bulkMark, safe to repeat without
#        unbounded row growth)
#
# Deliberately NOT covered: POST /api/v2/assessments/:id/submit — it's
# public/unauthenticated (a separate, already-flagged rate-limiting gap,
# see SECURITY_CHECKLIST.md) and duplicate-submission checking means a
# realistic test needs a fresh respondentId per request; left as a
# follow-up rather than bolted on here.

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

API_URL="${API_URL:-http://localhost:3001}"
TEST_DURATION="${TEST_DURATION:-15s}"
CONCURRENT_USERS="${CONCURRENT_USERS:-50}"
THREADS=$((CONCURRENT_USERS / 10 < 1 ? 1 : CONCURRENT_USERS / 10))
LOGIN_EMAIL="${LOGIN_EMAIL:-admin1@school.edu}"
LOGIN_PASSWORD="${LOGIN_PASSWORD:-admin123}"

RESULTS_DIR="load-test-business-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$RESULTS_DIR"

echo ""
echo -e "${BLUE}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Disha Load Testing - Authenticated Business Endpoints  ║${NC}"
echo -e "${BLUE}║   $(date '+%Y-%m-%d %H:%M:%S')                          ║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${BLUE}Pre-Test Verification${NC}"
if ! curl -s -f "$API_URL/health" > /dev/null; then
    echo -e "${RED}❌ API is not responding at $API_URL${NC}"
    exit 1
fi
echo -e "${GREEN}✅ API is running${NC}"

if ! command -v wrk &> /dev/null; then
    echo -e "${RED}❌ wrk is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}✅ wrk is installed${NC}"

echo -e "${YELLOW}Logging in as $LOGIN_EMAIL...${NC}"
LOGIN_RESPONSE=$(curl -s -X POST "$API_URL/api/v2/auth/login" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"$LOGIN_EMAIL\",\"password\":\"$LOGIN_PASSWORD\"}")

TOKEN=$(echo "$LOGIN_RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['accessToken'])" 2>/dev/null || true)
SCHOOL_ID=$(echo "$LOGIN_RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['user']['schoolId'])" 2>/dev/null || true)

if [ -z "$TOKEN" ] || [ "$TOKEN" = "None" ]; then
    echo -e "${RED}❌ Login failed — check LOGIN_EMAIL/LOGIN_PASSWORD and that the seed data is loaded${NC}"
    echo "$LOGIN_RESPONSE"
    exit 1
fi
echo -e "${GREEN}✅ Logged in, schoolId=$SCHOOL_ID${NC}"

echo -e "${YELLOW}Fetching a real active assessment and student roster for this school...${NC}"
ASSESSMENT_ID=$(curl -s "$API_URL/api/v2/assessments/school/$SCHOOL_ID" \
    -H "Authorization: Bearer $TOKEN" | \
    python3 -c "import sys,json; d=json.load(sys.stdin); a=[x for x in d if x.get('status')=='active']; print((a[0] if a else d[0])['id'])" 2>/dev/null || true)

STUDENT_IDS_JSON=$(curl -s "$API_URL/api/v2/students/school/$SCHOOL_ID" \
    -H "Authorization: Bearer $TOKEN" | \
    python3 -c "
import sys, json
d = json.load(sys.stdin)
ids = [s['id'] for s in d[:10]]
print(json.dumps(ids))
" 2>/dev/null || echo "[]")

if [ -z "$ASSESSMENT_ID" ] || [ "$ASSESSMENT_ID" = "None" ]; then
    echo -e "${RED}❌ Could not find an assessment for school $SCHOOL_ID — seed data may be missing${NC}"
    exit 1
fi
STUDENT_COUNT=$(echo "$STUDENT_IDS_JSON" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))")
if [ "$STUDENT_COUNT" -eq 0 ]; then
    echo -e "${RED}❌ No students found for school $SCHOOL_ID — seed data may be missing${NC}"
    exit 1
fi
echo -e "${GREEN}✅ assessmentId=$ASSESSMENT_ID, $STUDENT_COUNT students${NC}"

ATTENDANCE_RECORDS=$(python3 -c "
import json
ids = json.loads('''$STUDENT_IDS_JSON''')
print(json.dumps([{'studentId': i, 'status': 'Present'} for i in ids]))
")
ATTENDANCE_BODY=$(python3 -c "
import json
records = json.loads('''$ATTENDANCE_RECORDS''')
print(json.dumps({'schoolId': '$SCHOOL_ID', 'date': '2026-07-17', 'records': records}))
")

LUA_SCRIPT="$RESULTS_DIR/business-endpoints.lua"
cat > "$LUA_SCRIPT" <<LUAEOF
-- Generated by load-test-business.sh — real token/IDs from a live login,
-- not placeholders. Cycles GET students/assessments/reports and one
-- idempotent POST attendance/bulk per thread.
local token = "Bearer $TOKEN"
local body_attendance = [==[$ATTENDANCE_BODY]==]

local reqs = {
  { method = "GET",  path = "/api/v2/students/school/$SCHOOL_ID" },
  { method = "GET",  path = "/api/v2/assessments/school/$SCHOOL_ID" },
  { method = "GET",  path = "/api/v2/reports/school/$SCHOOL_ID/performance?startDate=2026-01-01&endDate=2026-07-17" },
  { method = "POST", path = "/api/v2/attendance/bulk", body = body_attendance },
}

local counter = 0

-- Globals (not locals) so each worker thread's final values can be read
-- back via thread:get() in done() below — wrk runs each thread in its own
-- Lua state, so a per-thread status_counts[status] table populated in
-- response() is invisible to done() (which runs in the setup thread's
-- separate state) unless surfaced through named globals this way.
status_2xx = 0
status_4xx = 0
status_5xx = 0
status_other = 0

request = function()
  counter = counter + 1
  local r = reqs[(counter % #reqs) + 1]
  local headers = {}
  headers["Authorization"] = token
  headers["Content-Type"] = "application/json"
  return wrk.format(r.method, r.path, headers, r.body)
end

response = function(status, headers, body)
  if status >= 200 and status < 300 then
    status_2xx = status_2xx + 1
  elseif status >= 400 and status < 500 then
    status_4xx = status_4xx + 1
  elseif status >= 500 then
    status_5xx = status_5xx + 1
  else
    status_other = status_other + 1
  end
end

threads = {}
function setup(thread)
  table.insert(threads, thread)
end

done = function(summary, latency, requests)
  local total_2xx, total_4xx, total_5xx, total_other = 0, 0, 0, 0
  for _, thread in ipairs(threads) do
    total_2xx = total_2xx + (thread:get("status_2xx") or 0)
    total_4xx = total_4xx + (thread:get("status_4xx") or 0)
    total_5xx = total_5xx + (thread:get("status_5xx") or 0)
    total_other = total_other + (thread:get("status_other") or 0)
  end
  io.write(string.format(
    "\n--- Response status breakdown ---\n  2xx: %d\n  4xx: %d\n  5xx: %d\n  other: %d\n",
    total_2xx, total_4xx, total_5xx, total_other
  ))
end
LUAEOF

echo ""
echo -e "${BLUE}Test Configuration${NC}"
echo "  API URL: $API_URL"
echo "  Duration: $TEST_DURATION"
echo "  Concurrent Users: $CONCURRENT_USERS"
echo "  Threads: $THREADS"
echo "  Endpoints: students list, assessments list, school performance report, attendance bulk mark (round-robin)"
echo "  Results: $RESULTS_DIR"
echo ""

echo -e "${YELLOW}Running mixed authenticated business-endpoint test...${NC}"
wrk -t"$THREADS" -c"$CONCURRENT_USERS" -d"$TEST_DURATION" \
    --latency \
    -s "$LUA_SCRIPT" \
    "$API_URL" 2>&1 | tee "$RESULTS_DIR/business-mixed.txt"

echo ""
echo -e "${GREEN}✅ Business endpoint load test complete!${NC}"
echo ""
echo "Results saved to: $RESULTS_DIR"
echo ""
